### ISSUE TITLE
Use more standard versions

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/recipe-blog#24]
Follow on from https://github.com/silverstripe/recipe-blog/pull/23

The approach there to using a self provision + installer rather than a standard provision is correct

Currently most recipes use recipe-cms ^4 instead of a lock-steped version such as 4.x-dev or 4.8.x-dev e.g.
- https://github.com/silverstripe/recipe-content-blocks/blob/2/composer.json#L9
- https://github.com/silverstripe/recipe-collaboration/blob/1/composer.json#L9

Cow will automatically convert either .x-dev or ^ to the correct stable tag.

### ACs
- update all recipes in cwp-recipe-kitchen sink to change silverstripe/recipe-cms to 4.8.x-dev
- on merge-up, change it to 4.x-dev

### PRs
- [x] https://github.com/silverstripe/recipe-blog/pull/25 (steve)
- [x] https://github.com/silverstripe/recipe-services/pull/12
- [x] recipe-core (nothing to do)
- [x] https://github.com/silverstripe/recipe-form-building/pull/12
- [x] https://github.com/silverstripe/recipe-authoring-tools/pull/12
- [x] https://github.com/silverstripe/cwp-recipe-core/pull/20
- [x] cwp-recipe-cms (no change required)
- [x] https://github.com/silverstripe/cwp-recipe-search/pull/17 
- [x] https://github.com/silverstripe/recipe-content-blocks/pull/15
- [x] https://github.com/silverstripe/recipe-collaboration/pull/10
- [x] recipe-cms (nothing to do)
- [x] https://github.com/silverstripe/recipe-reporting-tools/pull/18

**Comment by maxime-rainville** [comment]
The following conclusions were reach from a Slack discussion:
- Recipes are meant to work only with specific tags of other recipes.
- When cow tags a new recipe release, it lockstep constraint like `^4` to specific tags.
- By default, recipes should be tested with `self-jobs-range.yml` (as opposed to `standard-jobs-range.yml`) because this build only tries to run the recipe against a specific release line.
  - if we don't do that, builds for specific tags will always fail because it will try to install versions that contradict the lockstep.
- Recipe composer constraints on dev branches should target what will be lockstep when cow tags the recipe:
  - e.g. If recipe-blog 2.8 requires recipe-cms 4.8, then recipe-blog 2.8.x-dev should require recipe-cms 4.8.x-dev
  - If we were to use a loose constraint than like `^4', builds would always install the next minor release even if the recipe is lockstep to an older patch release.

**Comment by maxime-rainville** [comment]
All the PRs have been merged and merged up.
